/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meter_system;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manager Dashboard\n"));

        jButton1.setText("View Tenant's Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Logs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Outstandings"));

        jLabel1.setText("Tenant1:");

        jLabel2.setText("Tenant2:");

        jLabel3.setText("Tenant3:");

        jLabel4.setText("Tenant4:");

        jLabel5.setText("Tenant5:");

        jLabel6.setText("Tenant6:");

        jLabel7.setText("Tenant7:");

        jLabel8.setText("Tenant8:");

        jLabel9.setText("Tenant9:");

        jLabel10.setText("Tenant10:");

        jLabel11.setText("jLabel11");
        jLabel11.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel11AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setText("jLabel11");
        jLabel12.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel12AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel13.setText("jLabel11");
        jLabel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel13AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel14.setText("jLabel11");
        jLabel14.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel14AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel15.setText("jLabel11");
        jLabel15.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel15AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel16.setText("jLabel11");
        jLabel16.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel16AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel17.setText("jLabel11");
        jLabel17.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel17AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel18.setText("jLabel11");
        jLabel18.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel18AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel19.setText("jLabel11");
        jLabel19.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel19AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel20.setText("jLabel11");
        jLabel20.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel20AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel23.setText("jLabel23");
        jLabel23.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel23AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel24.setText("jLabel24");
        jLabel24.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel24AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel25.setText("jLabel25");
        jLabel25.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel25AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel26.setText("jLabel26");
        jLabel26.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel26AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel27.setText("jLabel27");
        jLabel27.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel27AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel28.setText("jLabel28");
        jLabel28.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel28AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel29.setText("jLabel29");
        jLabel29.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel29AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel30.setText("jLabel30");
        jLabel30.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel30AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel31.setText("jLabel31");
        jLabel31.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel31AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel32.setText("jLabel32");
        jLabel32.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel32AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20)
                    .addComponent(jLabel27)
                    .addComponent(jLabel32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Warn Tenant");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Total Usage:");

        jLabel22.setText("jLabel22");
        jLabel22.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel22AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jProgressBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        jButton4.setText("Back to Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(326, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        tenantoverview db = new tenantoverview();
        db.pack();
        db.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        JTextField user = new JTextField();
        JTextField alert = new JTextField();


        Object[] message = {
            "Username Number (must be from 1 to 10):", user,
            "Alert:", alert,
        };
        
        int option = JOptionPane.showConfirmDialog(null, message, "Prepay Topup", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION)
        {
            // Assigning values
            String use = user.getText();
            String aler = alert.getText();
            boolean validatedigit = Validation.validatedigit(use);
            
            // Validation for digits
            if(validatedigit==false){
                JOptionPane.showMessageDialog(null, "Please enter only digits for username section");
            }    
            
            
            boolean validatext = Validation.validatealpha(aler);
            int userparsed = Integer.parseInt(use);
            
      
            
            if( userparsed < 1 || userparsed > 10 ){
                JOptionPane.showMessageDialog(null, " Invalid Input,please choose ID between 1 and 10.");
            }
            
            else if (validatext==false) {
                JOptionPane.showMessageDialog(null, "Please enter only alphabets for alerts section");
            }

            
            else {
                
                // Parsing Variables     
                String Tenat = "tenant";
                dataupdate dup = new dataupdate();
                dup.setUsername(Tenat+userparsed);
                dup.setAlert(aler);
                dataupdate.updatealerts(dup);
                JOptionPane.showMessageDialog(null, "Alert Succesfully Sent");
                
            }
        }

            
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        Logspopup lg = new Logspopup();
        lg.pack();
        lg.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel12AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel12AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant1");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel12.setText("None");
        }
        else {
        jLabel12.setText(outstand.toString());
        }
        
    }//GEN-LAST:event_jLabel12AncestorAdded

    private void jLabel11AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel11AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant2");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel11.setText("None");
        }
        else {
        jLabel11.setText(outstand.toString());
        }
        
        
    }//GEN-LAST:event_jLabel11AncestorAdded

    private void jLabel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel13AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant3");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel13.setText("None");
        }
        else {
        jLabel13.setText(outstand.toString());
        }
        
        
    }//GEN-LAST:event_jLabel13AncestorAdded

    private void jLabel15AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel15AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant4");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel15.setText("None");
        }
        else {
        jLabel15.setText(outstand.toString());
        }
        
        
    }//GEN-LAST:event_jLabel15AncestorAdded

    private void jLabel14AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel14AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant5");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel14.setText("None");
        }
        else {
        jLabel14.setText(outstand.toString());
        }
        
        
    }//GEN-LAST:event_jLabel14AncestorAdded

    private void jLabel16AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel16AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant6");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel16.setText("None");
        }
        else {
        jLabel16.setText(outstand.toString());
        }
        
    }//GEN-LAST:event_jLabel16AncestorAdded

    private void jLabel17AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel17AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant7");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = usage - topup;
        if (outstand <= 0){
        jLabel17.setText("None");
        }
        else {
        jLabel17.setText(outstand.toString());
        }
        
    }//GEN-LAST:event_jLabel17AncestorAdded

    private void jLabel18AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel18AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant8");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel18.setText("None");
        }
        else {
        jLabel18.setText(outstand.toString());
        }
    }//GEN-LAST:event_jLabel18AncestorAdded

    private void jLabel19AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel19AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant9");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel19.setText("None");
        }
        else {
        jLabel19.setText(outstand.toString());
        }
        
    }//GEN-LAST:event_jLabel19AncestorAdded

    private void jLabel20AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel20AncestorAdded
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant10");
        Integer usage;
        Integer topup;
        Integer outstand;
        usage = dup2.getUsage();
        topup = dup2.getToptup();
        outstand = topup - usage;
        Integer absolute = Math.abs(outstand);
        if (outstand <= 0){
        jLabel20.setText("None");
        }
        else {
        jLabel20.setText(outstand.toString());
        }
    }//GEN-LAST:event_jLabel20AncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login lgn = new Login();
        this.dispose();
        lgn.setVisible(true); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel22AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel22AncestorAdded
        
        dataupdate dup1 = dataupdate.Retrievetenant("tenant1");
        Integer tnt1;
        tnt1 = dup1.getUsage();
        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant2");
        Integer tnt2;
        tnt2 = dup2.getUsage();
        
        dataupdate dup3 = dataupdate.Retrievetenant("tenant3");
        Integer tnt3;
        tnt3 = dup3.getUsage();
        
        dataupdate dup4 = dataupdate.Retrievetenant("tenant4");
        Integer tnt4;
        tnt4 = dup4.getUsage();
        
        dataupdate dup5 = dataupdate.Retrievetenant("tenant5");
        Integer tnt5;
        tnt5 = dup5.getUsage();
        
        dataupdate dup6 = dataupdate.Retrievetenant("tenant6");
        Integer tnt6;
        tnt6 = dup6.getUsage();
        
        dataupdate dup7 = dataupdate.Retrievetenant("tenant7");
        Integer tnt7;
        tnt7 = dup7.getUsage();
        
        dataupdate dup8 = dataupdate.Retrievetenant("tenant8");
        Integer tnt8;
        tnt8 = dup8.getUsage();
        
        dataupdate dup9 = dataupdate.Retrievetenant("tenant9");
        Integer tnt9;
        tnt9 = dup9.getUsage();
        
        dataupdate dup10 = dataupdate.Retrievetenant("tenant10");
        Integer tnt10;
        tnt10 = dup10.getUsage();
        
        Integer total = tnt1+tnt2+tnt3+tnt4+tnt5+tnt6+tnt7+tnt8+tnt9+tnt10;
        jLabel22.setText(total.toString()+" KW");
        jProgressBar1.setMaximum(1000);
        jProgressBar1.setValue(total);
        
        
    }//GEN-LAST:event_jLabel22AncestorAdded

    private void jProgressBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1AncestorAdded

    private void jLabel23AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel23AncestorAdded
        
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant1");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel23);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel23);
        }
     
    }//GEN-LAST:event_jLabel23AncestorAdded

    private void jLabel24AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel24AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant2");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel24);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel24);
        }
        
    }//GEN-LAST:event_jLabel24AncestorAdded

    private void jLabel25AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel25AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();
       
        dataupdate dup2 = dataupdate.Retrievetenant("tenant3");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel25);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel25);
        }
        
    }//GEN-LAST:event_jLabel25AncestorAdded

    private void jLabel26AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel26AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant4");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel26);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel26);
        }
        
    }//GEN-LAST:event_jLabel26AncestorAdded

    private void jLabel27AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel27AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant5");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel27);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel27);
        }
        
        
    }//GEN-LAST:event_jLabel27AncestorAdded

    private void jLabel28AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel28AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant6");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel28);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel28);
        }
        
    }//GEN-LAST:event_jLabel28AncestorAdded

    private void jLabel29AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel29AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant7");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel29);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel29);
        }
        
    }//GEN-LAST:event_jLabel29AncestorAdded

    private void jLabel30AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel30AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant8");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel30);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel30);
        }
        
    }//GEN-LAST:event_jLabel30AncestorAdded

    private void jLabel31AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel31AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant9");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel31);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel31);
        }
        
    }//GEN-LAST:event_jLabel31AncestorAdded

    private void jLabel32AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel32AncestorAdded
        
        paymentContext context = new paymentContext();
        paymentstate postpay = new postpaystate();
        paymentstate prepay = new prepaidstate();

        
        dataupdate dup2 = dataupdate.Retrievetenant("tenant10");
        Boolean ptype;
        ptype = dup2.gettype();
        
        if(ptype==false) {
            context.setState(postpay);
            context.Ptype(jLabel32);
        }
        else{
            context.setState(prepay);
            context.Ptype(jLabel32);
        }
        
        
    }//GEN-LAST:event_jLabel32AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
